service: chatwoot-openai-webhook
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 30
  vpc:
    securityGroupIds:
      - sg-054c22080d9d5cf15
    subnetIds:
      - subnet-0dd91cec8ce1a11bf
  environment:
    DB_HOST: 10.0.1.43
    DB_USER: postgres
    DB_NAME: chatwoot_db
    DB_PASSWORD: chatwoot
    DB_PORT: 5432
    NODE_ENV: production

functions:
  app:
    handler: main.handler
    vpc:
      securityGroupIds:
        - sg-054c22080d9d5cf15
      subnetIds:
        - subnet-0dd91cec8ce1a11bf
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With

      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With

plugins:
  - serverless-plugin-typescript
